version: 2
updates:
  - package-ecosystem: "nuget" 
    directory: "/templates/Library/NuGet" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions" 
    directory: "/"
    schedule:
      interval: "weekly" 
    groups:
       dev-dependencies:
          patterns:
            - "*-artifact"

  - package-ecosystem: "github-actions" 
    directory: "/templates/Library/NuGet/.github/workflows"
    schedule:
      interval: "weekly" 
    groups:
       dev-dependencies:
          patterns:
            - "*-artifact"

  - package-ecosystem: "github-actions" 
    directory: "/templates/Quickstart/BenchmarkApp/.github/workflows"
    schedule:
      interval: "weekly" 
    groups:
       dev-dependencies:
          patterns:
            - "*-artifact"
