name: Build

on:
  push:
    branches: [ main ]
    # Sequence of patterns matched against refs/tags
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  DOTNET_VERSION: 9.x

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.11.1
        with:
            use-github-auto-merge: true

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet pack --configuration Release -o . 
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NuGet
        path: ${{ github.workspace }}/*.nupkg

  test-library:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download NuGet Artifacts
        uses: actions/download-artifact@v5
        with:
          name: NuGet

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Test Template
        run: |
          dotnet new install $(Get-ChildItem -Path "BenjaminMichaelis.Dotnet.Templates.*.nupkg").Name
          mkdir TestLibrary
          Push-Location TestLibrary
          dotnet new bmichaelis.nuget
          dotnet test /p:TreatWarningsAsErrors=true
          dotnet pack --configuration Release -o ./NuGet

  test-quickstart-benchmarkconsole:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download NuGet Artifacts
        uses: actions/download-artifact@v5
        with:
          name: NuGet

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Test Template
        run: |
          dotnet new install $(Get-ChildItem -Path "BenjaminMichaelis.Dotnet.Templates.*.nupkg").Name
          mkdir TestQuickstartBenchmarkConsole
          Push-Location TestQuickstartBenchmarkConsole
          dotnet new bmichaelis.quickstart.benchmarkconsole
          dotnet test /p:TreatWarningsAsErrors=true
          cd TestQuickstartBenchmarkConsole
          dotnet run -c Release
          cd ..
          dotnet pack --configuration Release -o ./NuGet

  test-quickstart-consoleapp:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download NuGet Artifacts
        uses: actions/download-artifact@v5
        with:
          name: NuGet

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Test Template
        run: |
          dotnet new install $(Get-ChildItem -Path "BenjaminMichaelis.Dotnet.Templates.*.nupkg").Name
          mkdir TestQuickstartConsoleApp
          Push-Location TestQuickstartConsoleApp
          dotnet new bmichaelis.quickstart.consoleapp
          dotnet test /p:TreatWarningsAsErrors=true
          dotnet pack --configuration Release -o ./NuGet