name: Build

on:
  push:
    branches: [ main ]
    # Sequence of patterns matched against refs/tags
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  DOTNET_VERSION: 8.x

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
            use-github-auto-merge: true

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet pack --configuration Release -o . 
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NuGet
        path: ${{ github.workspace }}/*.nupkg

  test-library:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download NuGet Artifacts
        uses: actions/download-artifact@v4
        with:
          name: NuGet

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Test Template
        run: |
          dotnet new install $(Get-ChildItem -Path "BenjaminMichaelis.Dotnet.Templates.*.nupkg").Name
          mkdir TestLibrary
          Push-Location TestLibrary
          dotnet new bmichaelis.nuget
          dotnet test
          dotnet pack --configuration Release -o ./NuGet

  test-quickstart-benchmarkconsole:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download NuGet Artifacts
        uses: actions/download-artifact@v4
        with:
          name: NuGet

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Test Template
        run: |
          dotnet new install $(Get-ChildItem -Path "BenjaminMichaelis.Dotnet.Templates.*.nupkg").Name
          mkdir TestQuickstartBenchmarkConsole
          Push-Location TestQuickstartBenchmarkConsole
          dotnet new bmichaelis.quickstart.benchmarkconsole
          dotnet test
          cd TestQuickstartBenchmarkConsole
          dotnet run -c Release
          cd ..
          dotnet pack --configuration Release -o ./NuGet

  test-coalesce:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download NuGet Artifacts
        uses: actions/download-artifact@v4
        with:
          name: NuGet

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Test Template
        run: |
          dotnet new install $(Get-ChildItem -Path "BenjaminMichaelis.Dotnet.Templates.*.nupkg").Name
          mkdir TestCoalesce
          Push-Location TestCoalesce
          dotnet new bmichaelis.coalesce
          dotnet test
          git init
          git config user.email "myfakeemailforthistest@gmail.com"
          git config user.name "GithubBot"
          git add *
          git commit --all --message "Commiting so we have something to compare against to make sure Coalesce has run"

      - name: Ensure Coalesce has been run
        uses: benjaminmichaelis/check-intellitect-coalesce-action@v1
        with:
          working-directory: TestCoalesce/TestCoalesce.Web